# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10

  - name: Publications
    url: /publications/
    weight: 20

  # CV dropdown
  - name: CV
    identifier: cv
    weight: 30
    
  - name: Short CV
    parent: cv
    url: /uploads/resume.pdf
    weight: 10

  - name: Academic CV
    parent: cv
    url: /uploads/cv.pdf
    weight: 20
